### ISSUE TITLE
ResolvePackageNotFound: -pytorch3d=0.4.0

### ISSUE THREAD

**Issue by kkpetra** [Colin97/DeepMetaHandles#2]
I tried to create a environment form the yml but could not install pytorch3d("ResolvePackageNotFound"). Then I tried to install pytorch3d from other ways like through pip but "Could not find a version that satisfies the requirement pytorch3d=0.4.0". How can I fix this problem?

**Comment by Colin97** [comment]
Please follow https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md to use conda install.

**Comment by kkpetra** [comment]
> Please follow https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md to use conda install.
Thank you
